name: Comment on Issue

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  testRoute:
    name: Call maintainers
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
    if: github.event.sender.login != 'issuehunt-oss[bot]'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies (pnpm) # import remark-parse and unified
        run: pnpm i
      - name: Generate feedback
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { default: callMaintainer } = await import('${{ github.workspace }}/scripts/workflow/test-issue/call-maintainer.mjs')
            await callMaintainer({ github, context, core })
